### ISSUE TITLE
Bala fix issue

### ISSUE THREAD

**Issue by srinivas20152016** [bbaallaa/srinivas#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
dasfd

**Comment by srinivas20152016** [comment]
assigned to bala

**Comment by bbaallaa** [comment]
analyzed issue and assigning to srini

**Comment by srinivas20152016** [comment]
fixed changes are working fine/
